# Generated by Django 5.2.8 on 2025-11-14 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0004_company_locations_remove_job_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatushistory',
            options={'verbose_name': 'Application Status History', 'verbose_name_plural': 'Application Status Histories'},
        ),
        migrations.RenameField(
            model_name='applicationstatushistory',
            old_name='new_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='old_status',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='application_job_id_2b6ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='application_applica_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_on'], name='application_applied_7d8bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application'], name='application_applica_a170d6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['status'], name='application_status_39dbfb_idx'),
        ),
    ]
