# Generated by Django 5.2.8 on 2025-11-13 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'city'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('executive', 'Executive')], default='entry', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=50),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='jobs_compan_slug_d69c17_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified'], name='jobs_compan_is_veri_39966a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='jobs_compan_industr_e7d565_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'city'], name='jobs_locati_country_fa0451_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_remote'], name='jobs_locati_is_remo_161c31_idx'),
        ),
    ]
