# Generated by Django 5.2.8 on 2025-11-14 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_location_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(related_name='companies', to='jobs.location'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['website_url'], name='jobs_compan_website_2019b1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='jobs_job_company_9ee5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'category'], name='jobs_job_is_acti_9e9ad0_idx'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ManyToManyField(related_name='jobs', to='jobs.location'),
        ),
    ]
